apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hajer-site-http
  namespace: phdstudio
spec:
  entryPoints:
    - web
  routes:
    # Todas as requisições HTTP redirecionam para HTTPS
    - match: Host(`hajir.drahaabdalla.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: hajer-web-service
          port: 80
      middlewares:
        - name: redirect-https
          namespace: phdstudio

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hajer-site
  namespace: phdstudio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hajir.drahaabdalla.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: hajer-web-service
          port: 80
      middlewares:
        - name: security-headers
          namespace: phdstudio
        - name: compress
          namespace: phdstudio
  tls:
    certResolver: le

